server:
  port: 0

spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: matching-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.exchange.common.*
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer