server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: ws-broadcaster
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.HashMap
        spring.json.use.type.headers: false
